### ISSUE TITLE
Error: Cannot find module '@actions/core' on the main

### ISSUE THREAD

**Issue by vladsovetov** [Legorooj/skip-ci#4]
We use this github action
```
name: PR

on: pull_request

jobs:
  lint:
    name: lint + test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: ^7.14.2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - id: skip_ci
        uses: Legorooj/skip-ci@v1
        with:
          pattern: '\[skip\snew\]'
          ...
```

and yesterday (approximately 16 hours ago) it started to fail with the next error
![Screen Capture_select-area_20230620120106](https://github.com/Legorooj/skip-ci/assets/11698108/f40a6580-2736-4b59-bebb-f1bfcb393de5)
